name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Deploy Bicep file
      run: |
        az deployment group create --resource-group ${{ secrets.AZURE_RG }} --template-file ./Userstorys/Userstory1/Userstory1.bicep --parameters location=westeurope --mode complete

    - name: Deploy Bicep file
      run: |
        az deployment group create --resource-group ${{ secrets.AZURE_RG }} --template-file ./Userstorys/Userstory2/Userstory2.bicep --parameters location=westeurope --mode complete

    - name: Deploy Bicep file
      run: |
        az deployment group create --resource-group ${{ secrets.AZURE_RG }} --template-file ./Userstorys/Userstory3/Userstory3.bicep --parameters location=westeurope --mode complete
