name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: https://github.com/Niklas574/DevOps/blob/master/Userstorys/Userstory1/Userstory1.bicep
        parameters: 'location="westeurope"'
        failOnStdErr: false
    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: https://github.com/Niklas574/DevOps/blob/master/Userstorys/Userstory2/Userstory2.bicep
        parameters: 'location="westeurope"'
        failOnStdErr: false
    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: https://github.com/Niklas574/DevOps/blob/master/Userstorys/Userstory3/Userstory3.bicep
        parameters: 'location="westeurope"'
        failOnStdErr: false

