name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file 1
        run: |
            az deployment group create --resource-group ${{ secrets.AZURE_RG }} --name Userstory1Deployment --template-file ./Userstorys/Userstory1/Userstory1.bicep --parameters location=westeurope --mode complete

      - name: Deploy Bicep file 2
        run: |
             az deployment group create --resource-group ${{ secrets.AZURE_RG }} --name Userstory2Deployment --template-file ./Userstorys/Userstory2/Userstory2.bicep --parameters location=westeurope --mode complete
          
      - name: Deploy Bicep file 3
        run: |
            az deployment group create --resource-group ${{ secrets.AZURE_RG }} --name Userstory3Deployment --template-file ./Userstorys/Userstory3/Userstory3.bicep --parameters location=westeurope --mode complete
